// <auto-generated />
namespace MVC_HandsOn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class genreadd3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genreadd3));
        
        string IMigrationMetadata.Id
        {
            get { return "201711182011346_genreadd3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
